sudo: required

language: ruby

env:
  - DOCKER_COMPOSE_VERSION=1.20.1

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Generate Certificates
  - openssl genrsa -out .travis/wildcard.key 2048
  - openssl req -nodes -newkey rsa:2048 -keyout  .travis/wildcard.key -out  .travis/wildcard.csr -subj "/C=US/ST=Wisconsin/L=Middleon/O=US Geological Survey/OU=WMA/CN=*"
  - openssl x509 -req -days 9999 -in .travis/wildcard.csr -signkey .travis/wildcard.key  -out .travis/wildcard.crt
  # Run NGINX server within Travis
  - docker run -d -p 443:443 -p 80:80 -v ${PWD}/.travis/nginx.conf:/etc/nginx/nginx.conf -v ${PWD}/.travis/wildcard.crt:/etc/nginx/wildcard.crt -v ${PWD}/.travis/wildcard.key:/etc/nginx/wildcard.key nginx:latest && sleep 5
  # Pull against localhost - will be proxied by NGINX to Artifactory
  - docker pull localhost/wma/wma-spring-boot-base:0.0.1
  # Tag the pulled image to match the internal name of the Artifactory server
  - docker tag localhost/wma/wma-spring-boot-base:0.0.1 cidasdpdasartip.cr.usgs.gov:8447/wma/wma-spring-boot-base:0.0.1


install:
  - docker build -t aqcu-lookups .
  - docker-compose -f docker-compose.yml up -d --build

script:
  - docker ps | grep -q aqcu-lookups
